// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: service/inventory_service.proto

package grpcconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	grpc "server/pkg/grpc"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// InventoryServiceName is the fully-qualified name of the InventoryService service.
	InventoryServiceName = "InventoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InventoryServiceFetchInventoryProcedure is the fully-qualified name of the InventoryService's
	// FetchInventory RPC.
	InventoryServiceFetchInventoryProcedure = "/InventoryService/FetchInventory"
	// InventoryServiceAddInventoryProcedure is the fully-qualified name of the InventoryService's
	// AddInventory RPC.
	InventoryServiceAddInventoryProcedure = "/InventoryService/AddInventory"
)

// InventoryServiceClient is a client for the InventoryService service.
type InventoryServiceClient interface {
	// ユーザの在庫を取得
	FetchInventory(context.Context, *connect_go.Request[grpc.User]) (*connect_go.Response[grpc.Inventory], error)
	// ユーザの在庫に食材を追加
	AddInventory(context.Context, *connect_go.Request[grpc.Item]) (*connect_go.Response[grpc.Void], error)
}

// NewInventoryServiceClient constructs a client for the InventoryService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInventoryServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) InventoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &inventoryServiceClient{
		fetchInventory: connect_go.NewClient[grpc.User, grpc.Inventory](
			httpClient,
			baseURL+InventoryServiceFetchInventoryProcedure,
			opts...,
		),
		addInventory: connect_go.NewClient[grpc.Item, grpc.Void](
			httpClient,
			baseURL+InventoryServiceAddInventoryProcedure,
			opts...,
		),
	}
}

// inventoryServiceClient implements InventoryServiceClient.
type inventoryServiceClient struct {
	fetchInventory *connect_go.Client[grpc.User, grpc.Inventory]
	addInventory   *connect_go.Client[grpc.Item, grpc.Void]
}

// FetchInventory calls InventoryService.FetchInventory.
func (c *inventoryServiceClient) FetchInventory(ctx context.Context, req *connect_go.Request[grpc.User]) (*connect_go.Response[grpc.Inventory], error) {
	return c.fetchInventory.CallUnary(ctx, req)
}

// AddInventory calls InventoryService.AddInventory.
func (c *inventoryServiceClient) AddInventory(ctx context.Context, req *connect_go.Request[grpc.Item]) (*connect_go.Response[grpc.Void], error) {
	return c.addInventory.CallUnary(ctx, req)
}

// InventoryServiceHandler is an implementation of the InventoryService service.
type InventoryServiceHandler interface {
	// ユーザの在庫を取得
	FetchInventory(context.Context, *connect_go.Request[grpc.User]) (*connect_go.Response[grpc.Inventory], error)
	// ユーザの在庫に食材を追加
	AddInventory(context.Context, *connect_go.Request[grpc.Item]) (*connect_go.Response[grpc.Void], error)
}

// NewInventoryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInventoryServiceHandler(svc InventoryServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	inventoryServiceFetchInventoryHandler := connect_go.NewUnaryHandler(
		InventoryServiceFetchInventoryProcedure,
		svc.FetchInventory,
		opts...,
	)
	inventoryServiceAddInventoryHandler := connect_go.NewUnaryHandler(
		InventoryServiceAddInventoryProcedure,
		svc.AddInventory,
		opts...,
	)
	return "/.InventoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InventoryServiceFetchInventoryProcedure:
			inventoryServiceFetchInventoryHandler.ServeHTTP(w, r)
		case InventoryServiceAddInventoryProcedure:
			inventoryServiceAddInventoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInventoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInventoryServiceHandler struct{}

func (UnimplementedInventoryServiceHandler) FetchInventory(context.Context, *connect_go.Request[grpc.User]) (*connect_go.Response[grpc.Inventory], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("InventoryService.FetchInventory is not implemented"))
}

func (UnimplementedInventoryServiceHandler) AddInventory(context.Context, *connect_go.Request[grpc.Item]) (*connect_go.Response[grpc.Void], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("InventoryService.AddInventory is not implemented"))
}
