// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: service/user_service.proto

package serviceconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	grpc "github.com/mokumoku-party/banmeshi/server/pkg/grpc"
	_ "github.com/mokumoku-party/banmeshi/server/pkg/grpc/service"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceLoginProcedure is the fully-qualified name of the UserService's Login RPC.
	UserServiceLoginProcedure = "/UserService/Login"
)

// UserServiceClient is a client for the UserService service.
type UserServiceClient interface {
	// ユーザでログインする
	Login(context.Context, *connect_go.Request[grpc.User]) (*connect_go.Response[grpc.Void], error)
}

// NewUserServiceClient constructs a client for the UserService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &userServiceClient{
		login: connect_go.NewClient[grpc.User, grpc.Void](
			httpClient,
			baseURL+UserServiceLoginProcedure,
			opts...,
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	login *connect_go.Client[grpc.User, grpc.Void]
}

// Login calls UserService.Login.
func (c *userServiceClient) Login(ctx context.Context, req *connect_go.Request[grpc.User]) (*connect_go.Response[grpc.Void], error) {
	return c.login.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the UserService service.
type UserServiceHandler interface {
	// ユーザでログインする
	Login(context.Context, *connect_go.Request[grpc.User]) (*connect_go.Response[grpc.Void], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	userServiceLoginHandler := connect_go.NewUnaryHandler(
		UserServiceLoginProcedure,
		svc.Login,
		opts...,
	)
	return "/.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceLoginProcedure:
			userServiceLoginHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) Login(context.Context, *connect_go.Request[grpc.User]) (*connect_go.Response[grpc.Void], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("UserService.Login is not implemented"))
}
